name : Esteira de Validacao Java
on:
  push:
    branches: [ "main" ]

jobs:
  compilar:
    runs-on: ubuntu-latest

    steps: 
      - name: Baixando o codigo no servidor
        uses: actions/checkout@v4
        
      - name: Instalando o Java JDK no Servidor
        uses: actions/setup-java@v4
        with: 
          java-version: '17'
          distribution: 'temurin'
      - name: Compilando Sistema
        run: javac Validados.java

      - name: Executando Sistema
        run: java Validados